remote_theme: chrisrhymes/bulma-clean-theme
tagline: B Ravi Kiran
email: beedotkiran@gmail.com
fixed_navbar: top
permalink: pretty
paginate: 5

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

livereload: true
